export default iconsData = [
  {
    id: '1',
    title: 'On going sync',
    value: 4787,
    iconName: 'sync',
    iconColor: '#03B4B4',
    iconBackgroundColor: '#D9F5F5',
  },
  {
    id: '2',
    title: 'Connected Users',
    value: 113,
    iconName: 'user',
    iconColor: '#6E53A2',
    iconBackgroundColor: '#E8E1F6',
  },
  {
    id: '3',
    title: 'WO',
    value: 1713,
    iconName: 'setting',
    iconColor: '#CC0D59',
    iconBackgroundColor: '#F6E1F0',
  },
  {
    id: '4',
    title: 'On going sync',
    value: 4787,
    iconName: 'customerservice',
    iconColor: '#DCD918',
    iconBackgroundColor: '#FDFED8',
  },
  {
    id: '5',
    title: 'Connected Users',
    value: 113,
    iconName: 'book',
    iconColor: '#2E86AB',
    iconBackgroundColor: '#DFEFF6',
  },
  {
    id: '6',
    title: 'WO',
    value: 1713,
    iconName: 'clockcircleo',
    iconColor: '#564138',
    iconBackgroundColor: '#E7DEDA',
  },
];
