export default secondCardData = [
  {
    id: '1',
    type: 'Completed Gauge',
    title: 'Critical Work',
    value: 61,
    min: 10,
    max: 60,
    warning: 50,
  },
  {
    id: '2',
    type: 'Completed Gauge',
    title: 'Resources',
    value: 61,
    min: 20,
    max: 70,
    warning: 61,
  },
  {
    id: '3',
    type: 'Completed Gauge',
    title: 'Resources',
    value: 40,
    min: 10,
    max: 60,
    warning: 50,
  },
  {
    id: '4',
    type: 'Incompleted Gauge',
    title: 'Resources',
    value: 13,
    min: 10,
    max: 60,
    warning: 50,
  },
  {
    id: '4',
    type: 'Incompleted Gauge',
    title: 'Resources',
    value: 50,
    min: 10,
    max: 60,
    warning: 50,
  },
  {
    id: '5',
    type: 'Incompleted Gauge',
    title: 'Resources',
    value: 10,
    min: 10,
    max: 60,
    warning: 50,
  },
];
